Repository scrapy/scrapy, pull requests merged in 2019-09, with the labels that each got.

#4022 Fix the item exporter example
  docs/topics/exporters.rst
Labels: bug, docs

#4016 Crawling rules: make link extractors optional
  docs/topics/spiders.rst
  scrapy/spiders/crawl.py
  tests/test_spider.py
Labels: enhancement, link extraction

#4015 Remove deprecated xlib module
  .coveragerc
  conftest.py
  debian/scrapy.lintian-overrides
  scrapy/xlib/__init__.py
  scrapy/xlib/pydispatch.py
  scrapy/xlib/tx.py
  tests/test_pydispatch_deprecated.py
Labels: cleanup

#4033 Fix documentation typo: accesible → accessible
  scrapy/utils/request.py
Labels: bug, docs

#3999 Provide complete API documentation coverage of scrapy.item
  docs/conf.py
  docs/topics/items.rst
  scrapy/item.py
  tests/test_item.py
Labels: cleanup, docs, enhancement
