Repository scrapy/scrapy, pull requests merged in 2019-12, with the labels that each got.

#4213 Update overview.rst | Fix an inconsistency
  docs/intro/overview.rst
Labels: docs, enhancement

#4212 Convert the relative imports to absolute imports
  scrapy/__init__.py
  scrapy/contracts/default.py
  scrapy/core/downloader/__init__.py
  scrapy/core/downloader/handlers/http.py
  scrapy/core/downloader/handlers/s3.py
  scrapy/linkextractors/__init__.py
  scrapy/linkextractors/regex.py
Labels: cleanup

#4195 Keep 2 spaces between code and inline comments
  pytest.ini
  scrapy/core/downloader/webclient.py
  scrapy/core/engine.py
  scrapy/core/scraper.py
  scrapy/exporters.py
  scrapy/settings/default_settings.py
  scrapy/spiders/feed.py
  scrapy/utils/console.py
  tests/test_command_fetch.py
  tests/test_downloader_handlers.py
  tests/test_engine.py
  tests/test_http_request.py
  tests/test_pipeline_media.py
  tests/test_spidermiddleware_referer.py
  tests/test_utils_defer.py
  tests/test_utils_spider.py
Labels: cleanup

#4179 Make tox configuration more user friendly
  .travis.yml
  docs/contributing.rst
  tox.ini
Labels: enhancement

#4000 Add errback parameter to scrapy.spiders.crawl.Rule
  docs/topics/spiders.rst
  scrapy/spiders/crawl.py
  tests/mockserver.py
  tests/spiders.py
  tests/test_crawl.py
Labels: enhancement

#4190 Make developer-tools doctests pass
  docs/_tests/quotes.html
  docs/topics/developer-tools.rst
  pytest.ini
Labels: CI, docs, enhancement

#4164 Improve the performance of the DOWNLOAD_DELAY test
  tests/test_crawl.py
Labels: CI, enhancement

#4140 Use the latest Python version to build the documentation
  .readthedocs.yml
  .travis.yml
  tox.ini
Labels: CI, enhancement

#4249 Use Python 3.7 to build the documentation
  .readthedocs.yml
  .travis.yml
Labels: bug, docs

#4143 Do not indent doctests from the documentation unnecessarily
  docs/intro/tutorial.rst
  docs/news.rst
  docs/topics/dynamic-content.rst
  docs/topics/items.rst
  docs/topics/leaks.rst
  docs/topics/loaders.rst
  docs/topics/selectors.rst
  docs/topics/shell.rst
  docs/topics/stats.rst
Labels: cleanup, docs

#4045 Provide complete API documentation coverage of scrapy.linkextractors
  docs/conf.py
  docs/topics/link-extractors.rst
  pytest.ini
  scrapy/linkextractors/__init__.py
  scrapy/linkextractors/lxmlhtml.py
  tests/test_linkextractors.py
Labels: docs, enhancement

#3869 [MRG+1][Py3] Check for 'return' with arguments inside generators
  scrapy/core/scraper.py
  scrapy/utils/datatypes.py
  scrapy/utils/misc.py
  tests/test_utils_datatypes.py
  tests/test_utils_misc/test_return_with_argument_inside_generator.py
Labels: Python 3, enhancement, logging

#4193 Use super().__init__ in BaseItemExporter subclasses
  scrapy/exporters.py
Labels: cleanup

#4252 Rephrasing documentation for image and file pipelines
  docs/topics/media-pipeline.rst
Labels: docs, enhancement
