Repository scrapy/scrapy, pull requests merged in 2020-01, with the labels that each got.

#4057 Response.follow_all
  docs/intro/tutorial.rst
  docs/topics/request-response.rst
  scrapy/http/response/__init__.py
  scrapy/http/response/text.py
  tests/sample_data/link_extractor/linkextractor.html
  tests/sample_data/link_extractor/linkextractor_no_href.html
  tests/test_http_response.py
  tests/test_linkextractors.py
Labels: enhancement, link extraction

#4008 Request: remove restriction about errback without callback
  scrapy/http/request/__init__.py
  tests/test_http_request.py
Labels: enhancement

#4126 Download handlers: from_crawler factory method, take crawler in __init__
  scrapy/core/downloader/handlers/__init__.py
  scrapy/core/downloader/handlers/datauri.py
  scrapy/core/downloader/handlers/file.py
  scrapy/core/downloader/handlers/ftp.py
  scrapy/core/downloader/handlers/http10.py
  scrapy/core/downloader/handlers/http11.py
  scrapy/core/downloader/handlers/s3.py
  tests/test_downloader_handlers.py
Labels: backward-incompatible

#4227 Name resolver with IPv6 support
  docs/faq.rst
  docs/topics/settings.rst
  pytest.ini
  scrapy/crawler.py
  scrapy/resolver.py
  scrapy/settings/default_settings.py
  tests/CrawlerProcess/alternative_name_resolver.py
  tests/CrawlerProcess/default_name_resolver.py
  tests/test_crawler.py
Labels: enhancement

#3566 [MRG+1] change _retry() in RetryMiddleware log from debug to error
  scrapy/downloadermiddlewares/retry.py
Labels: backward-incompatible
