Repository scrapy/scrapy, pull requests merged in 2020-10, with the labels that each got.

#4822 Simplify TLS logging for the modern pyOpenSSL.
  scrapy/core/downloader/tls.py
Labels: cleanup

#4820 Drop the conditional code for old Twisted.
  scrapy/core/downloader/tls.py
Labels: cleanup

#4818 Crawl rule: remove deprecated code
  scrapy/spiders/crawl.py
  tests/test_spider.py
Labels: cleanup

#4775 Documentation of link extractor usage
  docs/index.rst
  docs/topics/link-extractors.rst
  scrapy/link.py
Labels: docs

#4817 Tests: use classes instead of paths in settings
  tests/test_dupefilters.py
  tests/test_logformatter.py
  tests/test_pipelines.py
  tests/test_request_attribute_binding.py
  tests/test_request_cb_kwargs.py
  tests/test_spidermiddleware_output_chain.py
Labels: CI, cleanup

#4835 Do not consider about: URLs invalid
  scrapy/http/request/__init__.py
  tests/test_http_request.py
Labels: bug
