Repository scrapy/scrapy, pull requests merged in 2020-07, with the labels that each got.

#4652 Docs: Simplify dataclass example in item loader page
  docs/topics/loaders.rst
Labels: docs

#4653 Update the OpenSSL cipher list format link
  docs/topics/settings.rst
Labels: docs

#4673 Remove backslash
  scrapy/cmdline.py
  scrapy/commands/crawl.py
  scrapy/commands/fetch.py
  scrapy/commands/genspider.py
  scrapy/commands/startproject.py
  scrapy/commands/view.py
  scrapy/core/engine.py
  scrapy/downloadermiddlewares/redirect.py
  scrapy/downloadermiddlewares/retry.py
  scrapy/extensions/memusage.py
  scrapy/http/request/form.py
  scrapy/http/response/text.py
  scrapy/link.py
  scrapy/settings/__init__.py
  scrapy/utils/benchserver.py
  scrapy/utils/conf.py
  scrapy/utils/curl.py
  scrapy/utils/ossignal.py
  scrapy/utils/response.py
  scrapy/utils/spider.py
  tests/test_downloadermiddleware_httpcompression.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_selector.py
  tests/test_settings/__init__.py
  tests/test_spider.py
  tests/test_spidermiddleware_referer.py
  tests/test_utils_curl.py
  tests/test_utils_defer.py
  tests/test_utils_iterators.py
  tests/test_utils_request.py
  tests/test_utils_response.py
  tests/test_utils_sitemap.py
  tests/test_utils_url.py
  tests/test_webclient.py
Labels: cleanup

#4504 Upgrade PyPy for CI, and test both 3.5 (oldest) and 3.6 (newest)
  .travis.yml
  docs/faq.rst
  docs/intro/install.rst
  setup.py
  tests/test_proxy_connect.py
  tests/test_utils_python.py
  tests/test_webclient.py
  tox.ini
Labels: CI, enhancement

#4254 Change Scraper API to call internal `_parse` method
  docs/topics/spiders.rst
  scrapy/core/scraper.py
  scrapy/spiders/__init__.py
  scrapy/spiders/crawl.py
  scrapy/spiders/feed.py
  tests/spiders.py
  tests/test_crawl.py
  tests/test_spider.py
Labels: enhancement

#4690 Remove monkeypatches module from mypy section in setup.cfg
  setup.cfg
Labels: cleanup
