Repository scrapy/scrapy, pull requests merged in 2020-05, with the labels that each got.

#4525 Flake8: remove W504 code
  pytest.ini
  scrapy/contracts/__init__.py
  scrapy/downloadermiddlewares/redirect.py
  scrapy/extensions/telnet.py
  scrapy/linkextractors/__init__.py
  scrapy/spidermiddlewares/referer.py
  scrapy/utils/gz.py
  tests/test_utils_http.py
Labels: cleanup

#4538 Flake8: remove E127
  pytest.ini
  scrapy/core/downloader/handlers/ftp.py
  scrapy/core/engine.py
  scrapy/utils/deprecate.py
  scrapy/utils/request.py
  tests/spiders.py
  tests/test_closespider.py
  tests/test_downloader_handlers.py
  tests/test_downloadermiddleware_decompression.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_http_request.py
  tests/test_selector.py
  tests/test_spidermiddleware_httperror.py
  tests/test_utils_url.py
Labels: cleanup

#4519 Test the latest Ubuntu along the latest Python
  .travis.yml
  tests/test_crawler.py
Labels: CI, enhancement

#4542 Flake8: remove E122 and E124
  pytest.ini
  tests/test_dupefilters.py
  tests/test_exporters.py
  tests/test_linkextractors.py
  tests/test_utils_sitemap.py
  tests/test_webclient.py
Labels: cleanup

#4544 Flake8: remove E129
  pytest.ini
  tests/test_utils_iterators.py
Labels: cleanup

#4543 Flake8: remove E126
  pytest.ini
  scrapy/core/downloader/contextfactory.py
  scrapy/core/downloader/handlers/s3.py
  scrapy/core/downloader/webclient.py
  scrapy/downloadermiddlewares/retry.py
  scrapy/spiderloader.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_downloadermiddleware_retry.py
  tests/test_http_request.py
  tests/test_pipeline_crawl.py
  tests/test_webclient.py
Labels: cleanup

#4557 Flake8: remove E111, E114, E116, E117, E121
  pytest.ini
  scrapy/pipelines/files.py
  scrapy/selector/unified.py
  tests/test_spidermiddleware_httperror.py
Labels: cleanup

#4554 Remove lambda attributes in default link extractor
  scrapy/linkextractors/lxmlhtml.py
  tests/test_linkextractors.py
Labels: enhancement, link extraction

#4205 Add bytes_received signal
  docs/topics/signals.rst
  scrapy/core/downloader/handlers/http11.py
  scrapy/signals.py
  tests/test_downloader_handlers.py
  tests/test_engine.py
Labels: enhancement

#4541 Pickle: use protocol 4, update tests
  pytest.ini
  scrapy/exporters.py
  scrapy/extensions/httpcache.py
  scrapy/extensions/spiderstate.py
  scrapy/squeues.py
  tests/test_squeues.py
Labels: enhancement

#4566 Flake8: remove F841
  pytest.ini
  tests/pipelines.py
  tests/test_crawler.py
  tests/test_dependencies.py
  tests/test_extension_telnet.py
  tests/test_feedexport.py
  tests/test_item.py
  tests/test_pipeline_images.py
  tests/test_spidermiddleware_referer.py
  tests/test_utils_defer.py
  tests/test_utils_deprecate.py
  tests/test_utils_signal.py
Labels: cleanup

#4558 Flake8: Remove E741
  pytest.ini
  scrapy/shell.py
  scrapy/spiders/sitemap.py
  scrapy/utils/log.py
  tests/test_command_version.py
  tests/test_crawl.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_dupefilters.py
  tests/test_pipeline_media.py
  tests/test_proxy_connect.py
  tests/test_squeues.py
  tests/test_utils_log.py
  tests/test_utils_misc/__init__.py
  tests/test_utils_signal.py
Labels: cleanup

#4545 Flake8: Remove E128
  pytest.ini
  scrapy/commands/__init__.py
  scrapy/commands/fetch.py
  scrapy/commands/genspider.py
  scrapy/commands/parse.py
  scrapy/commands/settings.py
  scrapy/commands/shell.py
  scrapy/commands/startproject.py
  scrapy/commands/version.py
  scrapy/core/downloader/contextfactory.py
  scrapy/core/downloader/handlers/ftp.py
  scrapy/core/engine.py
  scrapy/extensions/httpcache.py
  scrapy/item.py
  scrapy/mail.py
  scrapy/responsetypes.py
  scrapy/utils/defer.py
  scrapy/utils/log.py
  scrapy/utils/response.py
  scrapy/utils/signal.py
  scrapy/utils/url.py
  tests/test_command_parse.py
  tests/test_command_shell.py
  tests/test_contracts.py
  tests/test_downloader_handlers.py
  tests/test_downloadermiddleware_httpproxy.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_downloadermiddleware_retry.py
  tests/test_dupefilters.py
  tests/test_http_request.py
  tests/test_http_response.py
  tests/test_item.py
  tests/test_linkextractors.py
  tests/test_logformatter.py
  tests/test_mail.py
  tests/test_middleware.py
  tests/test_pipeline_crawl.py
  tests/test_pipeline_media.py
  tests/test_settings/__init__.py
  tests/test_spiderloader/__init__.py
  tests/test_spidermiddleware_httperror.py
  tests/test_spidermiddleware_offsite.py
  tests/test_utils_conf.py
  tests/test_utils_iterators.py
  tests/test_utils_reqser.py
  tests/test_utils_request.py
  tests/test_utils_sitemap.py
  tests/test_webclient.py
Labels: cleanup

#4518 Run tests with Python 3.5.0
  .travis.yml
  README.rst
  docs/faq.rst
  docs/intro/install.rst
  tests/test_proxy_connect.py
Labels: CI, enhancement

#4534 Deprecate scrapy.item.BaseItem
  docs/faq.rst
  docs/topics/items.rst
  scrapy/commands/parse.py
  scrapy/contracts/default.py
  scrapy/core/scraper.py
  scrapy/exporters.py
  scrapy/item.py
  scrapy/shell.py
  scrapy/spiders/feed.py
  scrapy/utils/misc.py
  scrapy/utils/serialize.py
  tests/test_item.py
  tests/test_loader.py
  tests/test_utils_spider.py
Labels: cleanup

#4237 Set flake8-max-line-length to 119
  pytest.ini
  scrapy/cmdline.py
  scrapy/robotstxt.py
  scrapy/spiders/crawl.py
  tests/test_command_shell.py
  tests/test_crawler.py
  tests/test_downloader_handlers.py
  tests/test_downloadermiddleware_httpcompression.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_dupefilters.py
  tests/test_exporters.py
  tests/test_feedexport.py
  tests/test_http_request.py
  tests/test_http_response.py
  tests/test_linkextractors.py
  tests/test_pipeline_files.py
  tests/test_pipeline_images.py
  tests/test_request_cb_kwargs.py
  tests/test_responsetypes.py
  tests/test_selector.py
  tests/test_spider.py
  tests/test_spidermiddleware_output_chain.py
  tests/test_spidermiddleware_referer.py
  tests/test_utils_iterators.py
  tests/test_utils_request.py
  tests/test_utils_sitemap.py
  tests/test_utils_url.py
Labels: cleanup, discuss

#4587 logging.rst: remove unused, misleading import
  docs/topics/logging.rst
Labels: bug, docs

#2400 [MRG+1] CookiesMiddleware: keep cookies from 'Cookie' request header, fix encoding
  docs/topics/downloader-middleware.rst
  docs/topics/logging.rst
  scrapy/downloadermiddlewares/cookies.py
  tests/test_downloadermiddleware_cookies.py
Labels: enhancement

#4559 Stop response download from signal handler
  docs/faq.rst
  docs/topics/exceptions.rst
  docs/topics/request-response.rst
  docs/topics/signals.rst
  scrapy/core/downloader/handlers/http11.py
  scrapy/exceptions.py
  scrapy/utils/signal.py
  tests/spiders.py
  tests/test_crawl.py
  tests/test_engine.py
Labels: enhancement

#4568 Remove _monkeypatches, import-related Flake8 codes
  pytest.ini
  scrapy/__init__.py
  scrapy/_monkeypatches.py
  scrapy/linkextractors/__init__.py
  scrapy/selector/__init__.py
  scrapy/spiders/__init__.py
Labels: cleanup
