Repository scrapy/scrapy, pull requests merged in 2020-04, with the labels that each got.

#4472 Remove empty _RequestBodyProducer for POST requests
  scrapy/core/downloader/handlers/http11.py
Labels: cleanup

#4469 Fix pycodestyle E502 ("the backslash is redundant between brackets")
  pytest.ini
  scrapy/commands/genspider.py
  scrapy/commands/shell.py
  scrapy/core/downloader/middleware.py
  scrapy/core/engine.py
  scrapy/mail.py
  scrapy/utils/deprecate.py
  tests/test_pipeline_media.py
Labels: cleanup

#4468 Fix pycodestyle E2XX (whitespace)
  pytest.ini
  scrapy/core/downloader/tls.py
  scrapy/dupefilters.py
  scrapy/pipelines/files.py
  scrapy/pipelines/images.py
  scrapy/pipelines/media.py
  tests/test_crawl.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_http_response.py
  tests/test_spidermiddleware_referer.py
  tests/test_utils_iterators.py
  tests/test_utils_url.py
  tests/test_webclient.py
Labels: cleanup

#4480 Pin version for Sphinx and extensions, configure hoverxref
  docs/conf.py
  docs/requirements.txt
  docs/topics/downloader-middleware.rst
  docs/topics/settings.rst
Labels: CI, docs

#3940 Get server IP address for HTTP/1.1 Responses
  conftest.py
  docs/topics/request-response.rst
  scrapy/core/downloader/__init__.py
  scrapy/core/downloader/handlers/http11.py
  scrapy/http/response/__init__.py
  tests/CrawlerRunner/ip_address.py
  tests/mockserver.py
  tests/test_crawl.py
  tests/test_crawler.py
Labels: enhancement

#4471 Fix pycodestyle E731 ("do not assign a lambda expression, use a def")
  pytest.ini
  scrapy/commands/fetch.py
  scrapy/commands/parse.py
  scrapy/core/downloader/webclient.py
  scrapy/linkextractors/__init__.py
  scrapy/linkextractors/lxmlhtml.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_exporters.py
  tests/test_pipeline_media.py
  tests/test_utils_python.py
  tests/test_utils_signal.py
Labels: cleanup

#4507 Docs: replace deprecated FEED_FORMAT and FEED_URI settings
  docs/topics/practices.rst
Labels: docs

#4440 Remove assertions from production code
  scrapy/commands/__init__.py
  scrapy/contracts/default.py
  scrapy/core/downloader/middleware.py
  scrapy/core/engine.py
  scrapy/core/scraper.py
  scrapy/crawler.py
  scrapy/http/request/__init__.py
  scrapy/pipelines/files.py
  scrapy/utils/iterators.py
  scrapy/utils/reactor.py
  tests/test_utils_iterators.py
Labels: backward-incompatible, cleanup

#4499 Cover Scrapy 2.1 in the release notes
  docs/news.rst
  docs/topics/request-response.rst
Labels: docs

#4517 Run quick tests first in Travis CI
  .travis.yml
Labels: CI, enhancement

#4521 Simplify the asyncio Tox environment
  .travis.yml
  tox.ini
Labels: CI, enhancement

#4522 Remove TOXENV from .travis.yml unless needed
  .travis.yml
Labels: CI, enhancement
