Repository scrapy/scrapy, pull requests merged in 2020-08, with the labels that each got.

#4707 change super() syntax
  extras/qpsclient.py
  scrapy/commands/view.py
  scrapy/contracts/default.py
  scrapy/core/downloader/contextfactory.py
  scrapy/core/downloader/handlers/http11.py
  scrapy/core/downloader/tls.py
  scrapy/core/spidermw.py
  scrapy/crawler.py
  scrapy/downloadermiddlewares/redirect.py
  scrapy/exceptions.py
  scrapy/exporters.py
  scrapy/http/headers.py
  scrapy/http/request/form.py
  scrapy/http/request/json_request.py
  scrapy/http/request/rpc.py
  scrapy/http/response/text.py
  scrapy/item.py
  scrapy/linkextractors/__init__.py
  scrapy/linkextractors/lxmlhtml.py
  scrapy/pipelines/files.py
  scrapy/pipelines/images.py
  scrapy/resolver.py
  scrapy/selector/unified.py
  scrapy/settings/__init__.py
  scrapy/spidermiddlewares/httperror.py
  scrapy/spiders/crawl.py
  scrapy/spiders/init.py
  scrapy/spiders/sitemap.py
  scrapy/squeues.py
  scrapy/statscollectors.py
  scrapy/utils/datatypes.py
  scrapy/utils/deprecate.py
  scrapy/utils/log.py
  scrapy/utils/serialize.py
  scrapy/utils/testsite.py
  tests/spiders.py
  tests/test_command_parse.py
  tests/test_commands.py
  tests/test_contracts.py
  tests/test_downloader_handlers.py
  tests/test_downloadermiddleware_httpcache.py
  tests/test_downloadermiddleware_robotstxt.py
  tests/test_exporters.py
  tests/test_http_request.py
  tests/test_http_response.py
  tests/test_item.py
  tests/test_linkextractors.py
  tests/test_loader.py
  tests/test_loader_deprecated.py
  tests/test_logformatter.py
  tests/test_middleware.py
  tests/test_pipeline_media.py
  tests/test_request_left.py
  tests/test_robotstxt_interface.py
  tests/test_scheduler.py
  tests/test_spidermiddleware_httperror.py
Labels: cleanup

#4723 test_utils_iterators.py: support Windows the right way
  .gitattributes
  tests/test_utils_iterators.py
Labels: CI, Windows

#4705 Cover our deprecation policy in the documentation
  docs/contributing.rst
  docs/versioning.rst
Labels: docs, enhancement

#4090 Fix references to Python types in parameter type fields
  docs/topics/contracts.rst
  docs/topics/email.rst
  docs/topics/exporters.rst
  docs/topics/leaks.rst
  docs/topics/link-extractors.rst
  docs/topics/request-response.rst
  scrapy/crawler.py
  scrapy/robotstxt.py
  scrapy/settings/__init__.py
  scrapy/signalmanager.py
Labels: bug, docs

#4165 Merge Twisted’s deprecated HTTPClientFactory into ScrapyHTTPClientFactory
  scrapy/core/downloader/webclient.py
Labels: CI, cleanup

#4512 Allow overwriting feeds
  docs/faq.rst
  docs/intro/overview.rst
  docs/intro/tutorial.rst
  docs/topics/feed-exports.rst
  scrapy/commands/__init__.py
  scrapy/extensions/feedexport.py
  scrapy/utils/conf.py
  scrapy/utils/ftp.py
  scrapy/utils/python.py
  tests/ftpserver.py
  tests/mockserver.py
  tests/requirements-py3.txt
  tests/test_commands.py
  tests/test_feedexport.py
  tests/test_utils_conf.py
  tests/test_utils_python.py
Labels: enhancement

#4735 Re-enable TLS 1.2 in cipher tests.
  tests/mockserver.py
Labels: CI

#4742 Update Python version references after dropping support for 3.5
  README.rst
  docs/intro/install.rst
  docs/intro/tutorial.rst
  docs/topics/coroutines.rst
  scrapy/__init__.py
  scrapy/utils/defer.py
  scrapy/utils/gz.py
  setup.py
  tests/requirements-py3.txt
  tests/test_crawl.py
  tests/test_item.py
  tests/test_proxy_connect.py
  tox.ini
Labels: cleanup

#4691 Typing: annotate a few Spider attributes
  scrapy/spiders/__init__.py
  scrapy/spiders/crawl.py
  setup.cfg
  tests/spiders.py
Labels: cleanup, enhancement

#4722 Do not let umask affect the permissions of startproject-generated files
  scrapy/utils/template.py
  tests/test_commands.py
Labels: bug

#4764 Merge back tests/py36/_test_crawl.py.
  conftest.py
  tests/py36/_test_crawl.py
  tests/spiders.py
  tests/test_crawl.py
Labels: cleanup
