Repository scrapy/scrapy, pull requests merged in 2020-02, with the labels that each got.

#4304 Remove elusive six occurrence from tox.ini
  tox.ini
Labels: cleanup

#4311 Make METAREFRESH_IGNORE_TAGS an empty list by default
  docs/topics/downloader-middleware.rst
  scrapy/settings/default_settings.py
  tests/test_downloadermiddleware_redirect.py
Labels: backward-incompatible

#4272 Spider middleware: catch spider callback exceptions early
  scrapy/core/spidermw.py
  scrapy/utils/python.py
  tests/test_spidermiddleware_output_chain.py
Labels: bug

#4290 FilesPipeline.file_path has optional arguments
  docs/topics/media-pipeline.rst
Labels: bug, docs

#4197 [Docs] Fix Twisted links
  docs/conf.py
Labels: bug, docs

#4300 Deprecate overriding settings with SCRAPY-prefixed environment variables
  scrapy/utils/project.py
Labels: cleanup, discuss

#4188 LogFormatter error formatting
  scrapy/core/scraper.py
  scrapy/logformatter.py
  tests/test_logformatter.py
Labels: enhancement, logging

#4331 Implement Response.cb_kwargs
  docs/topics/request-response.rst
  scrapy/http/response/__init__.py
  tests/test_http_response.py
Labels: enhancement

#3884 Remove specifics of downstream request queues from scheduler
  scrapy/core/scheduler.py
  scrapy/pqueues.py
  scrapy/squeues.py
  tests/test_squeues.py
Labels: backward-incompatible

#4054 Expose certificate for HTTPS responses
  docs/topics/request-response.rst
  scrapy/core/downloader/handlers/http11.py
  scrapy/http/response/__init__.py
  tests/test_crawl.py
Labels: enhancement, https

#4370 Make BaseItemExporter’s dont_fail parameter keyword-only
  scrapy/exporters.py
Labels: backward-incompatible, enhancement

#4373 Fix the ReadTheDocs build
  .readthedocs.yml
Labels: bug, docs

#4375 Stop deprecation warnings on arbitrary SCRAPY-prefixed env vars
  scrapy/utils/project.py
  tests/test_utils_project.py
Labels: backward-incompatible, bug, discuss
