Repository scrapy/scrapy, pull requests merged in 2020-12, with the labels that each got.

#4899 Update links in installation guide
  docs/conf.py
  docs/intro/install.rst
Labels: docs

#4912 Remove deprecated SCRAPY_PICKLED_SETTINGS_TO_OVERRIDE
  scrapy/utils/project.py
Labels: cleanup

#4878 Response.protocol attribute
  docs/topics/request-response.rst
  scrapy/core/downloader/handlers/http11.py
  scrapy/core/downloader/webclient.py
  scrapy/http/response/__init__.py
  tests/test_downloader_handlers.py
Labels: enhancement

#4814 add pip 20.2 test for tox
  .travis.yml
  setup.py
  tests/requirements-py3.txt
  tests/test_dependencies.py
  tests/test_downloadermiddleware.py
  tests/test_proxy_connect.py
  tests/test_utils_signal.py
  tests/test_webclient.py
  tox.ini
Labels: hacktoberfest-accepted
