Repository scrapy/scrapy, pull requests merged in 2021-07, with the labels that each got.

#5200 [CI] fail-fast: false
  .github/workflows/checks.yml
  .github/workflows/tests-macos.yml
  .github/workflows/tests-ubuntu.yml
  .github/workflows/tests-windows.yml
Labels: CI

#5207 Make the pylint test pass
  .github/workflows/checks.yml
  .github/workflows/tests-ubuntu.yml
  pylintrc
Labels: CI

#5208 Pin the libxml2 version in CI as a newer one breaks lxml.
  .github/workflows/tests-ubuntu.yml
Labels: CI

#5215 Typing: switch to a newer version of MyPy to check types
  tests/CrawlerProcess/asyncio_deferred_signal.py
  tox.ini
Labels: CI, typing

#5209 Cleanup leftover boto2 code in S3DownloaderHandler
  scrapy/core/downloader/handlers/s3.py
Labels: cleanup

#4613 Update headless browser docs
  docs/topics/dynamic-content.rst
Labels: docs, enhancement

#5210 Add support for temporary security credential in AWS auth
  docs/topics/feed-exports.rst
  docs/topics/settings.rst
  scrapy/core/downloader/handlers/s3.py
  scrapy/extensions/feedexport.py
  scrapy/pipelines/files.py
  scrapy/pipelines/images.py
  tests/test_feedexport.py
  tox.ini
Labels: enhancement
