Repository scrapy/scrapy, pull requests merged in 2021-04, with the labels that each got.

#4974 Move lists closer to their introducing paragraph
  docs/_static/custom.css
  docs/conf.py
  docs/topics/exceptions.rst
  docs/topics/feed-exports.rst
  docs/topics/selectors.rst
  docs/topics/shell.rst
Labels: docs, enhancement

#4895 Some type hints
  scrapy/__init__.py
  scrapy/commands/__init__.py
  scrapy/commands/parse.py
  scrapy/contracts/__init__.py
  scrapy/http/cookies.py
  scrapy/item.py
  scrapy/mail.py
  scrapy/spidermiddlewares/referer.py
  scrapy/utils/httpobj.py
  scrapy/utils/request.py
  scrapy/utils/response.py
  scrapy/utils/trackref.py
  setup.cfg
Labels: cleanup, typing

#5076 Use __qualname__ in middleware handling.
  scrapy/core/downloader/middleware.py
  scrapy/core/spidermw.py
Labels: cleanup

#5095 Cleanup of slot handling in Scraper.
  scrapy/core/scraper.py
Labels: cleanup

#5077 Add typing for middleware and coroutine related code.
  scrapy/core/downloader/middleware.py
  scrapy/core/scraper.py
  scrapy/core/spidermw.py
  scrapy/middleware.py
  scrapy/utils/asyncgen.py
  scrapy/utils/defer.py
  scrapy/utils/python.py
Labels: typing

#5100 Additional typing for scraper and a small code change.
  scrapy/core/scraper.py
Labels: cleanup, typing

#5070 Include loading settings in `Running multiple spiders in the same precess` section
  docs/topics/practices.rst
Labels: docs, enhancement

#5090 Engine: deprecations and type hints
  docs/topics/telnetconsole.rst
  scrapy/core/engine.py
  scrapy/core/scraper.py
  scrapy/downloadermiddlewares/robotstxt.py
  scrapy/extensions/memusage.py
  scrapy/pipelines/media.py
  scrapy/shell.py
  scrapy/utils/engine.py
  tests/test_downloadermiddleware_robotstxt.py
  tests/test_engine.py
Labels: cleanup, enhancement, typing

#5106 Engine: remove unnecessary parameter
  scrapy/core/engine.py
Labels: cleanup

#5108 Dupefilter type hints
  scrapy/dupefilters.py
  scrapy/utils/request.py
Labels: enhancement, typing
