Repository scrapy/scrapy, pull requests merged in 2021-08, with the labels that each got.

#5221 Fixing tests for upcoming 3.10.
  .github/workflows/tests-ubuntu.yml
  scrapy/utils/signal.py
  tests/test_http_response.py
  tests/test_request_cb_kwargs.py
  tests/test_spiderloader/__init__.py
Labels: bug, CI

#5229 Disable builtin middlewares in spider middleware tests.
  tests/test_spidermiddleware.py
Labels: CI

#4039 Move documentation about avoiding bans into a topic of its own
  docs/index.rst
  docs/topics/avoiding-bans.rst
  docs/topics/practices.rst
Labels: enhancement, docs

#4178 Remove deprecated Spider.make_requests_from_url method
  scrapy/spiders/__init__.py
  tests/test_spider.py
Labels: discuss, cleanup

#5235 Fix/silence the Pylint messages added in 2.10.
  pylintrc
  scrapy/utils/conf.py
  scrapy/utils/deprecate.py
  tests/keys/__init__.py
  tests/test_downloader_handlers_http2.py
  tests/test_engine.py
  tests/test_exporters.py
  tests/test_http2_client_protocol.py
  tests/test_loader_deprecated.py
  tests/test_request_cb_kwargs.py
  tests/test_scheduler.py
  tests/test_utils_conf.py
  tests/test_utils_misc/__init__.py
Labels: enhancement, CI
