Repository scrapy/scrapy, pull requests merged in 2022-01, with the labels that each got.

#5352 Install the reactor after reading spider settings
  docs/news.rst
  docs/topics/practices.rst
  docs/topics/settings.rst
  scrapy/commands/shell.py
  scrapy/crawler.py
  scrapy/utils/log.py
  tests/CrawlerProcess/twisted_reactor_custom_settings.py
  tests/CrawlerProcess/twisted_reactor_custom_settings_conflict.py
  tests/CrawlerProcess/twisted_reactor_custom_settings_same.py
  tests/test_commands.py
  tests/test_crawler.py
Labels: enhancement, asyncio

#5334 Fix typing of middleware methods.
  scrapy/core/downloader/middleware.py
  scrapy/core/spidermw.py
  scrapy/middleware.py
Labels: typing

#1582 added: Doc for `scrapy.http.TextResponse.urljoin`
  docs/topics/request-response.rst
Labels: docs

#4966 Fix FEED_URI_PARAMS: custom params throws KeyError
  docs/topics/feed-exports.rst
  scrapy/extensions/feedexport.py
  tests/test_feedexport.py
Labels: backward-incompatible
