Repository scrapy/scrapy, pull requests merged in 2022-10, with the labels that each got.

#5657 CrawlSpider: add support for async callbacks
  scrapy/spiders/crawl.py
  scrapy/utils/asyncgen.py
  tests/spiders.py
  tests/test_crawl.py
Labels: enhancement, asyncio

#5667 Simplify the PyPy installation in CI
  .github/workflows/tests-ubuntu.yml
Labels: CI

#5672 Remove a pin on libxml2-dev.
  .github/workflows/tests-ubuntu.yml
Labels: CI, cleanup

#5668 Update tool versions
  .flake8
  conftest.py
  docs/_ext/scrapydocs.py
  scrapy/utils/testsite.py
  tests/CrawlerProcess/asyncio_deferred_signal.py
  tests/CrawlerProcess/asyncio_enabled_reactor.py
  tests/CrawlerProcess/reactor_default.py
  tests/CrawlerProcess/reactor_default_twisted_reactor_select.py
  tests/CrawlerProcess/reactor_select.py
  tests/CrawlerProcess/reactor_select_subclass_twisted_reactor_select.py
  tests/CrawlerProcess/reactor_select_twisted_reactor_select.py
  tests/test_http_response.py
  tox.ini
Labels: CI

#5577 add async callbacks support to parse
  scrapy/commands/parse.py
  tests/test_command_parse.py
Labels: enhancement, asyncio

#5688 Fix the flake8 per-file ignore syntax.
  .flake8
  scrapy/utils/url.py
  tests/test_loader.py
Labels: bug, CI, cleanup

#5695 ci: Update macos runner
  .github/workflows/tests-macos.yml
Labels: hacktoberfest-accepted
