Repository scrapy/scrapy, pull requests merged in 2023-10, with the labels that each got.

#6084 Update checkout action to version 4
  .github/workflows/checks.yml
  .github/workflows/publish.yml
  .github/workflows/tests-macos.yml
  .github/workflows/tests-ubuntu.yml
  .github/workflows/tests-windows.yml
Labels: CI

#6083 Adapt to the Python 3.12 final release
  .github/workflows/tests-macos.yml
  .github/workflows/tests-ubuntu.yml
  .github/workflows/tests-windows.yml
  tests/requirements.txt
  tests/test_downloader_handlers.py
  tests/test_feedexport.py
  tests/test_pipeline_files.py
Labels: CI

#6087 Change supported PyPy versions to 3.9 and 3.10.
  .github/workflows/tests-ubuntu.yml
  docs/conf.py
Labels: CI

#6097 Add typing hints to CaselessDict and Headers.
  scrapy/core/http2/stream.py
  scrapy/http/headers.py
  scrapy/http/request/__init__.py
  scrapy/http/response/__init__.py
  scrapy/http/response/text.py
  scrapy/utils/datatypes.py
  tests/test_http2_client_protocol.py
Labels: enhancement, typing

#6113 Remove some deprecated code
  scrapy/crawler.py
  scrapy/downloadermiddlewares/decompression.py
  scrapy/downloadermiddlewares/httpauth.py
  scrapy/downloadermiddlewares/httpcompression.py
  scrapy/dupefilters.py
  scrapy/extensions/feedexport.py
  scrapy/http/request/__init__.py
  scrapy/http/request/json_request.py
  scrapy/loader/common.py
  scrapy/loader/processors.py
  scrapy/pipelines/media.py
  scrapy/utils/misc.py
  tests/test_crawler.py
  tests/test_downloadermiddleware_decompression.py
  tests/test_downloadermiddleware_httpauth.py
  tests/test_downloadermiddleware_httpcompression.py
  tests/test_feedexport.py
  tests/test_loader_deprecated.py
  tests/test_pipeline_media.py
Labels: cleanup

#6112 Make shutdown tests more robust.
  tests/CrawlerProcess/sleeping.py
  tests/test_command_shell.py
  tests/test_crawler.py
Labels: bug, CI
