Repository scrapy/scrapy, pull requests merged in 2023-11, with the labels that each got.

#6130 Full typing for scrapy/spidermiddlewares.
  scrapy/spidermiddlewares/depth.py
  scrapy/spidermiddlewares/httperror.py
  scrapy/spidermiddlewares/offsite.py
  scrapy/spidermiddlewares/referer.py
  scrapy/spidermiddlewares/urllength.py
Labels: enhancement, typing

#6129 Full typing for scrapy/downloadermiddlewares.
  scrapy/downloadermiddlewares/ajaxcrawl.py
  scrapy/downloadermiddlewares/cookies.py
  scrapy/downloadermiddlewares/defaultheaders.py
  scrapy/downloadermiddlewares/downloadtimeout.py
  scrapy/downloadermiddlewares/httpauth.py
  scrapy/downloadermiddlewares/httpcache.py
  scrapy/downloadermiddlewares/httpcompression.py
  scrapy/downloadermiddlewares/httpproxy.py
  scrapy/downloadermiddlewares/redirect.py
  scrapy/downloadermiddlewares/retry.py
  scrapy/downloadermiddlewares/robotstxt.py
  scrapy/downloadermiddlewares/stats.py
  scrapy/downloadermiddlewares/useragent.py
  scrapy/http/cookies.py
  scrapy/robotstxt.py
  setup.cfg
Labels: enhancement, typing

#6134 Remove obsolete setters for body and url on Request and Response.
  scrapy/http/common.py
  scrapy/http/request/__init__.py
  scrapy/http/response/__init__.py
  scrapy/utils/iterators.py
Labels: discuss, cleanup

#6137 Fix and remove most of the entries from the mypy ignore list.
  scrapy/contracts/__init__.py
  scrapy/loader/__init__.py
  scrapy/pipelines/images.py
  scrapy/utils/testproc.py
  setup.cfg
  tests/mocks/dummydbm.py
  tests/test_exporters.py
  tests/test_http_request.py
  tests/test_linkextractors.py
  tests/test_loader.py
  tests/test_pipeline_crawl.py
  tests/test_pipeline_files.py
  tests/test_pipeline_images.py
  tests/test_request_cb_kwargs.py
  tests/test_scheduler.py
  tests/test_spidermiddleware_httperror.py
  tests/test_spidermiddleware_referer.py
  tests/test_utils_serialize.py
  tests/test_utils_url.py
Labels: enhancement, cleanup, typing

#6147 Improve the docs about Crawler attributes and settings initialization.
  docs/news.rst
  docs/topics/spiders.rst
Labels: docs

#5565 Extend Request.meta documentation
  docs/topics/request-response.rst
Labels: enhancement, docs
