Repository scrapy/scrapy, pull requests merged in 2023-06, with the labels that each got.

#5951 Actually run test_set_asyncio_event_loop().
  tests/test_utils_asyncio.py
Labels: bug, CI, asyncio

#5953 Drop Python 3.7 support
  .github/workflows/tests-macos.yml
  .github/workflows/tests-ubuntu.yml
  .github/workflows/tests-windows.yml
  .pre-commit-config.yaml
  README.rst
  docs/contributing.rst
  docs/intro/install.rst
  scrapy/__init__.py
  setup.py
  tox.ini
Labels: cleanup

#5925 Typing for scrapy/utils
  scrapy/crawler.py
  scrapy/resolver.py
  scrapy/spiderloader.py
  scrapy/utils/boto.py
  scrapy/utils/datatypes.py
  scrapy/utils/decorators.py
  scrapy/utils/defer.py
  scrapy/utils/deprecate.py
  scrapy/utils/display.py
  scrapy/utils/engine.py
  scrapy/utils/gz.py
  scrapy/utils/misc.py
  scrapy/utils/python.py
  scrapy/utils/reactor.py
  scrapy/utils/request.py
  scrapy/utils/serialize.py
  scrapy/utils/template.py
  scrapy/utils/test.py
  scrapy/utils/url.py
  scrapy/utils/versions.py
  tests/test_pipeline_files.py
  tox.ini
Labels: typing

#5963 fix: Return value instead of `SettingsAttribute` object when using `pop` method
  scrapy/settings/__init__.py
  tests/test_settings/__init__.py
Labels: bug
