Repository scrapy/scrapy, pull requests merged in 2023-04, with the labels that each got.

#5889 Typing improvements for some core components
  scrapy/core/downloader/__init__.py
  scrapy/core/engine.py
  scrapy/core/scheduler.py
  scrapy/core/scraper.py
  scrapy/core/spidermw.py
  scrapy/crawler.py
  scrapy/exceptions.py
  scrapy/logformatter.py
  scrapy/middleware.py
  scrapy/pipelines/__init__.py
  scrapy/signalmanager.py
  scrapy/statscollectors.py
  scrapy/utils/log.py
  scrapy/utils/misc.py
  scrapy/utils/reactor.py
  scrapy/utils/signal.py
  tox.ini
Labels: enhancement, typing

#5885 Replace get_func_args
  scrapy/utils/python.py
  tests/test_utils_python.py
Labels: enhancement, cleanup

#5896 Typing for scrapy/core/downloader
  scrapy/core/downloader/__init__.py
  scrapy/core/downloader/contextfactory.py
  scrapy/core/downloader/handlers/__init__.py
  scrapy/core/downloader/middleware.py
  scrapy/core/downloader/tls.py
  scrapy/core/downloader/webclient.py
  scrapy/utils/python.py
  scrapy/utils/ssl.py
Labels: enhancement, typing

#5908 Update tool versions
  .bandit.yml
  .pre-commit-config.yaml
  tox.ini
Labels: CI, cleanup
