Repository scrapy/scrapy, pull requests merged in 2023-09, with the labels that each got.

#6034 Update type hints for Twisted 23.8.0.
  scrapy/core/downloader/__init__.py
  scrapy/core/engine.py
  scrapy/core/scraper.py
  scrapy/logformatter.py
Labels: bug, CI, typing

#6036 Fix enabled addons not being logged
  scrapy/addons.py
  tests/test_addons.py
Labels: bug

#6045 Pin brotli for pypy tests.
  tests/requirements.txt
Labels: bug, CI

#6038 Change extensions/spiders/settings initialisation order, v2
  docs/topics/settings.rst
  docs/topics/spiders.rst
  scrapy/addons.py
  scrapy/commands/shell.py
  scrapy/core/engine.py
  scrapy/core/scraper.py
  scrapy/crawler.py
  scrapy/downloadermiddlewares/httpcache.py
  scrapy/downloadermiddlewares/retry.py
  scrapy/dupefilters.py
  scrapy/extensions/httpcache.py
  scrapy/settings/__init__.py
  scrapy/utils/log.py
  scrapy/utils/test.py
  tests/CrawlerProcess/args_settings.py
  tests/CrawlerProcess/asyncio_enabled_reactor_different_loop.py
  tests/CrawlerProcess/reactor_default_twisted_reactor_select.py
  tests/CrawlerProcess/reactor_select_subclass_twisted_reactor_select.py
  tests/CrawlerProcess/twisted_reactor_custom_settings_conflict.py
  tests/test_addons.py
  tests/test_commands.py
  tests/test_crawler.py
  tests/test_extension_periodic_log.py
  tests/test_scheduler.py
  tests/test_spider.py
Labels: enhancement, discuss

#6050 Improve the backwards compatibility for RetryMiddleware.EXCEPTIONS_TO_RETRY
  scrapy/downloadermiddlewares/retry.py
  tests/test_downloadermiddleware_retry.py
Labels: bug
