Repository scrapy/scrapy, pull requests merged in 2023-08, with the labels that each got.

#5950 Add-ons
  docs/index.rst
  docs/topics/addons.rst
  docs/topics/api.rst
  docs/topics/settings.rst
  scrapy/addons.py
  scrapy/crawler.py
  scrapy/middleware.py
  scrapy/settings/__init__.py
  scrapy/settings/default_settings.py
  scrapy/utils/misc.py
  sep/sep-021.rst
  tests/test_addons.py
  tests/test_middleware.py
  tests/test_utils_deprecate.py
Labels: enhancement

#5993 Deprecate the custom attribute of build_component_list().
  scrapy/utils/conf.py
  tests/test_utils_conf.py
Labels: cleanup

#5999 Enable Python 3.11 on Windows CI
  .github/workflows/tests-windows.yml
Labels: enhancement, CI

#5998 Remove deprecated `spider` parameter from engine
  scrapy/core/engine.py
  tests/test_engine.py
Labels: cleanup

#6003 Typing for scrapy/utils, second pass
  scrapy/commands/__init__.py
  scrapy/commands/fetch.py
  scrapy/commands/shell.py
  scrapy/contracts/__init__.py
  scrapy/exceptions.py
  scrapy/extensions/feedexport.py
  scrapy/http/response/text.py
  scrapy/selector/unified.py
  scrapy/spiderloader.py
  scrapy/spiders/__init__.py
  scrapy/utils/conf.py
  scrapy/utils/defer.py
  scrapy/utils/ftp.py
  scrapy/utils/iterators.py
  scrapy/utils/job.py
  scrapy/utils/log.py
  scrapy/utils/ossignal.py
  scrapy/utils/project.py
  scrapy/utils/response.py
  scrapy/utils/signal.py
  scrapy/utils/sitemap.py
  scrapy/utils/spider.py
  scrapy/utils/ssl.py
  scrapy/utils/testproc.py
  scrapy/utils/trackref.py
  tests/test_contracts.py
  tests/test_feedexport.py
  tox.ini
Labels: enhancement, typing

#6007 Remove deprecated PythonItemExporter.binary
  scrapy/exporters.py
  tests/test_exporters.py
Labels: cleanup

#6010 Remove deprecated CrawlerRunner.spiders.
  scrapy/crawler.py
  tests/test_crawler.py
Labels: cleanup

#6005 More typing for scrapy/*.py
  scrapy/core/scheduler.py
  scrapy/core/scraper.py
  scrapy/crawler.py
  scrapy/dupefilters.py
  scrapy/exceptions.py
  scrapy/link.py
  scrapy/logformatter.py
  scrapy/middleware.py
  scrapy/responsetypes.py
  scrapy/spiderloader.py
  scrapy/spiders/__init__.py
  scrapy/utils/request.py
Labels: enhancement, typing

#6014 Remove datetime.utcnow() usage
  scrapy/extensions/corestats.py
  scrapy/extensions/feedexport.py
  tests/keys/__init__.py
  tests/test_spiderstate.py
  tests/test_stats.py
Labels: cleanup

#6026 Forbid Twisted 23.8.0+
  setup.py
Labels: bug, CI
