Repository scrapy/scrapy, pull requests merged in 2024-10, with the labels that each got.

#6487 Remove the installation dependency on setuptools.
  setup.py
  tox.ini
Labels: cleanup

#6494 Misc typing improvements.
  scrapy/commands/check.py
  scrapy/commands/genspider.py
  scrapy/commands/parse.py
  scrapy/core/engine.py
  scrapy/core/scraper.py
  scrapy/core/spidermw.py
  scrapy/crawler.py
  scrapy/downloadermiddlewares/httpcompression.py
  scrapy/downloadermiddlewares/robotstxt.py
  scrapy/extensions/feedexport.py
  scrapy/pipelines/files.py
  scrapy/utils/defer.py
  tox.ini
Labels: enhancement, typing

#6499 Additional Python 3.7 and 3.8 cleanup, including Reppy support.
  docs/news.rst
  docs/topics/downloader-middleware.rst
  scrapy/robotstxt.py
  scrapy/utils/reactor.py
  tests/CrawlerProcess/asyncio_enabled_reactor.py
  tests/CrawlerProcess/asyncio_enabled_reactor_different_loop.py
  tests/CrawlerProcess/asyncio_enabled_reactor_same_loop.py
  tests/test_downloadermiddleware_robotstxt.py
  tests/test_robotstxt_interface.py
  tox.ini
Labels: cleanup

#6501 Filter test-time warnings.
  tests/test_crawl.py
  tests/test_crawler.py
  tests/test_downloadermiddleware_offsite.py
  tests/test_dupefilters.py
  tests/test_pipeline_crawl.py
  tests/test_scheduler.py
  tests/test_spiderloader/__init__.py
  tests/test_utils_asyncio.py
  tests/test_utils_datatypes.py
  tests/test_utils_misc/__init__.py
Labels: bug, CI

#6507 Explictly set html_baseurl on RTD.
  docs/conf.py
Labels: enhancement, docs

#6510 Remove code for unsupported Twisted.
  scrapy/mail.py
  tests/test_mail.py
Labels: cleanup

#6516 Added ignore statements for Windows specific typing issues
  scrapy/extensions/debug.py
  scrapy/utils/console.py
Labels: enhancement, Windows, typing

#6500 Deprecation removals.
  conftest.py
  docs/topics/commands.rst
  extras/scrapy_zsh_completion
  pytest.ini
  scrapy/commands/__init__.py
  scrapy/crawler.py
  scrapy/downloadermiddlewares/httpcompression.py
  scrapy/downloadermiddlewares/retry.py
  scrapy/extensions/feedexport.py
  scrapy/pipelines/images.py
  scrapy/utils/conf.py
  scrapy/utils/reactor.py
  scrapy/utils/request.py
  tests/test_crawler.py
  tests/test_downloader_handlers.py
  tests/test_downloadermiddleware_httpcompression.py
  tests/test_downloadermiddleware_retry.py
  tests/test_feedexport.py
  tests/test_pipeline_files.py
  tests/test_pipeline_images.py
  tests/test_utils_conf.py
  tox.ini
Labels: cleanup
