Repository scrapy/scrapy, pull requests merged in 2024-11, with the labels that each got.

#6522 Documentation added for Spider State in extensions.rst
  docs/topics/extensions.rst
  docs/topics/jobs.rst
Labels: hacktoberfest-accepted

#6524 Run and fix linkcheck.
  README.rst
  docs/conf.py
  docs/contributing.rst
  docs/faq.rst
  docs/index.rst
  docs/intro/install.rst
  docs/intro/overview.rst
  docs/intro/tutorial.rst
  docs/news.rst
  docs/topics/architecture.rst
  docs/topics/broad-crawls.rst
  docs/topics/deploy.rst
  docs/topics/developer-tools.rst
  docs/topics/downloader-middleware.rst
  docs/topics/dynamic-content.rst
  docs/topics/extensions.rst
  docs/topics/feed-exports.rst
  docs/topics/item-pipeline.rst
  docs/topics/items.rst
  docs/topics/media-pipeline.rst
  docs/topics/selectors.rst
  docs/topics/settings.rst
  extras/coverage-report.sh
  scrapy/downloadermiddlewares/ajaxcrawl.py
  scrapy/http/request/__init__.py
  scrapy/utils/request.py
  scrapy/utils/url.py
  tests/test_http_request.py
  tests/test_pipeline_crawl.py
  tests/test_pipeline_images.py
  tests/test_pipeline_media.py
Labels: bug, docs, cleanup

#6427 Update the outdated Item docstring.
  docs/topics/items.rst
  scrapy/item.py
Labels: bug, docs

#6519 Deprecate unused scrapy utils
  scrapy/utils/misc.py
  scrapy/utils/python.py
  scrapy/utils/request.py
  scrapy/utils/serialize.py
  scrapy/utils/test.py
  tests/test_utils_python.py
  tests/test_utils_request.py
Labels: hacktoberfest-accepted

#6531 Address some previously ignored pylint messages.
  conftest.py
  pylintrc
  scrapy/commands/crawl.py
  scrapy/commands/edit.py
  scrapy/commands/parse.py
  scrapy/contracts/__init__.py
  scrapy/core/downloader/handlers/__init__.py
  scrapy/core/downloader/handlers/ftp.py
  scrapy/core/downloader/middleware.py
  scrapy/core/engine.py
  scrapy/core/scheduler.py
  scrapy/core/spidermw.py
  scrapy/extensions/feedexport.py
  scrapy/http/request/form.py
  scrapy/mail.py
  scrapy/pipelines/files.py
  scrapy/resolver.py
  scrapy/settings/__init__.py
  scrapy/spidermiddlewares/referer.py
  scrapy/utils/conf.py
  scrapy/utils/console.py
  scrapy/utils/defer.py
  scrapy/utils/display.py
  scrapy/utils/log.py
  scrapy/utils/python.py
  scrapy/utils/reactor.py
  scrapy/utils/response.py
  scrapy/utils/trackref.py
  scrapy/utils/url.py
  tests/spiders.py
  tests/test_crawler.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_linkextractors.py
  tests/test_loader_deprecated.py
  tests/test_logformatter.py
  tests/test_pipeline_files.py
  tests/test_request_dict.py
  tests/test_spidermiddleware_referer.py
  tests/test_utils_datatypes.py
  tests/test_utils_defer.py
Labels: cleanup

#6540 Remove build_from_settings() and deprecate from_settings() code
  docs/topics/email.rst
  docs/topics/request-response.rst
  scrapy/core/downloader/contextfactory.py
  scrapy/dupefilters.py
  scrapy/extensions/feedexport.py
  scrapy/extensions/memusage.py
  scrapy/extensions/statsmailer.py
  scrapy/mail.py
  scrapy/middleware.py
  scrapy/pipelines/files.py
  scrapy/pipelines/images.py
  scrapy/pipelines/media.py
  scrapy/spidermiddlewares/urllength.py
  scrapy/utils/misc.py
  tests/test_dupefilters.py
  tests/test_middleware.py
  tests/test_pipeline_files.py
  tests/test_pipeline_images.py
  tests/test_pipeline_media.py
  tests/test_spidermiddleware_urllength.py
  tests/test_utils_misc/__init__.py
  tests/test_utils_request.py
  tests/test_webclient.py
Labels: enhancement, cleanup

#6545 Commit mitmproxy-dhparam.pem.
  tests/keys/mitmproxy-dhparam.pem
Labels: bug, CI

#6560 Add tests for DOWNLOADER_CLIENT_TLS_METHOD, remove dead code.
  scrapy/core/downloader/contextfactory.py
  tests/test_webclient.py
Labels: https, CI, cleanup
