Repository scrapy/scrapy, pull requests merged in 2025-03, with the labels that each got.

#6614 Extend BaseSettings with utils for add-ons
  docs/topics/addons.rst
  docs/topics/settings.rst
  scrapy/settings/__init__.py
  scrapy/utils/conf.py
  tests/test_settings/__init__.py
  tox.ini
Labels: enhancement

#6700 Converting tests to plain asserts, part 3.
  tests/test_downloadermiddleware.py
  tests/test_downloadermiddleware_ajaxcrawlable.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_downloadermiddleware_defaultheaders.py
  tests/test_downloadermiddleware_downloadtimeout.py
  tests/test_downloadermiddleware_httpauth.py
  tests/test_downloadermiddleware_httpcache.py
  tests/test_downloadermiddleware_httpcompression.py
  tests/test_downloadermiddleware_httpproxy.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_downloadermiddleware_retry.py
  tests/test_downloadermiddleware_robotstxt.py
  tests/test_downloadermiddleware_stats.py
  tests/test_downloadermiddleware_useragent.py
Labels: CI, cleanup

#6699 Converting tests to plain asserts, part 2.
  tests/test_addons.py
  tests/test_closespider.py
  tests/test_cmdline/__init__.py
  tests/test_cmdline_crawl_with_pipeline/__init__.py
  tests/test_command_check.py
  tests/test_command_fetch.py
  tests/test_command_parse.py
  tests/test_command_shell.py
  tests/test_command_version.py
  tests/test_commands.py
  tests/test_contracts.py
  tests/test_core_downloader.py
  tests/test_crawl.py
  tests/test_crawler.py
  tests/test_dependencies.py
  tests/test_downloaderslotssettings.py
  tests/test_dupefilters.py
  tests/test_engine.py
  tests/test_engine_stop_download_bytes.py
  tests/test_engine_stop_download_headers.py
  tests/test_webclient.py
Labels: CI, cleanup

#6701 Remove the Splash recommendation.
  docs/topics/dynamic-content.rst
Labels: docs, cleanup

#6702 Converting tests to plain asserts, part 4.
  tests/test_spider.py
  tests/test_spiderloader/__init__.py
  tests/test_spidermiddleware.py
  tests/test_spidermiddleware_depth.py
  tests/test_spidermiddleware_httperror.py
  tests/test_spidermiddleware_offsite.py
  tests/test_spidermiddleware_output_chain.py
  tests/test_spidermiddleware_referer.py
  tests/test_spidermiddleware_urllength.py
  tests/test_spiderstate.py
  tests/test_squeues.py
  tests/test_squeues_request.py
  tests/test_stats.py
Labels: CI, cleanup

#6703 Work around a queuelib test file close problem.
  tests/test_squeues.py
Labels: bug, CI

#6704 Drop tests/test_loader_deprecated.py.
  tests/test_loader_deprecated.py
Labels: CI, cleanup

#6709 Converting tests to plain asserts, part 6.
  tests/test_item.py
  tests/test_link.py
  tests/test_linkextractors.py
  tests/test_pipeline_crawl.py
  tests/test_pipeline_files.py
  tests/test_pipeline_images.py
  tests/test_pipeline_media.py
Labels: CI, cleanup

#6710 Converting tests to plain asserts, part 7.
  tests/test_downloader_handlers.py
  tests/test_downloader_handlers_http2.py
  tests/test_exporters.py
  tests/test_feedexport.py
  tests/test_http2_client_protocol.py
  tests/test_http_cookies.py
  tests/test_http_headers.py
Labels: CI, cleanup

#6711 Converting tests to plain asserts, part 8.
  tests/test_http_request.py
  tests/test_http_response.py
  tests/test_loader.py
  tests/test_settings/__init__.py
Labels: CI, cleanup

#6712 Converting tests to plain asserts, part 5.
  tests/test_logformatter.py
  tests/test_logstats.py
  tests/test_mail.py
  tests/test_middleware.py
  tests/test_pipelines.py
  tests/test_pqueues.py
  tests/test_proxy_connect.py
  tests/test_request_attribute_binding.py
  tests/test_request_cb_kwargs.py
  tests/test_request_dict.py
  tests/test_request_left.py
  tests/test_responsetypes.py
  tests/test_robotstxt_interface.py
  tests/test_scheduler.py
  tests/test_scheduler_base.py
  tests/test_selector.py
  tests/test_signals.py
  tests/test_toplevel.py
  tests/test_urlparse_monkeypatches.py
Labels: CI, cleanup

#6716 Better fix for test_non_pickable_object on Windows.
  tests/test_squeues.py
Labels: bug, CI

#6725 Convert remaining unittest assert* calls, use the tmp_path fixture.
  pyproject.toml
  scrapy/utils/test.py
  tests/test_downloadermiddleware_robotstxt.py
  tests/test_engine.py
  tests/test_pipeline_files.py
  tests/test_pipeline_images.py
  tests/test_utils_template.py
Labels: CI, cleanup

#6713 Enable AsyncioSelectorReactor by default.
  .github/workflows/tests-ubuntu.yml
  .github/workflows/tests-windows.yml
  conftest.py
  docs/topics/asyncio.rst
  docs/topics/media-pipeline.rst
  docs/topics/settings.rst
  scrapy/pipelines/images.py
  scrapy/settings/default_settings.py
  scrapy/templates/project/module/settings.py.tmpl
  scrapy/utils/log.py
  scrapy/utils/test.py
  tests/CrawlerProcess/asyncio_enabled_reactor.py
  tests/CrawlerProcess/reactor_default.py
  tests/CrawlerProcess/reactor_select.py
  tests/CrawlerRunner/ip_address.py
  tests/test_addons.py
  tests/test_crawl.py
  tests/test_crawler.py
  tests/test_dependencies.py
  tests/test_downloader_handlers.py
  tests/test_downloaderslotssettings.py
  tests/test_extension_periodic_log.py
  tests/test_pipeline_crawl.py
  tests/test_spider.py
  tests/test_utils_asyncio.py
  tox.ini
Labels: enhancement, asyncio

#6732 Don't install the reactor in is_asyncio_reactor_installed().
  docs/topics/asyncio.rst
  scrapy/utils/reactor.py
  tests/CrawlerProcess/asyncio_enabled_no_reactor.py
  tests/CrawlerProcess/asyncio_enabled_reactor.py
  tests/test_crawler.py
Labels: bug, asyncio

#6734 More docs about Deferred<->Future interoperability.
  docs/topics/asyncio.rst
  docs/topics/coroutines.rst
  scrapy/utils/defer.py
Labels: enhancement, docs, asyncio

#6735 Fix running simple tests with --reactor=default.
  conftest.py
Labels: bug, CI

#6741 feat: Add test analytics
  .github/workflows/tests-macos.yml
  .github/workflows/tests-ubuntu.yml
  .github/workflows/tests-windows.yml
  .gitignore
  tox.ini
Labels: enhancement, CI

#6743 Convert test_downloadermiddleware_robotstxt.py from callbacks to awaits.
  tests/test_downloadermiddleware_robotstxt.py
Labels: enhancement, CI
