Repository scrapy/scrapy, pull requests merged in 2025-09, with the labels that each got.

#7033 Extract @_warn_spider_arg.
  scrapy/core/downloader/__init__.py
  scrapy/core/downloader/handlers/__init__.py
  scrapy/core/scraper.py
  scrapy/pipelines/media.py
  scrapy/spidermiddlewares/base.py
  scrapy/spidermiddlewares/depth.py
  scrapy/spidermiddlewares/httperror.py
  scrapy/statscollectors.py
  scrapy/utils/decorators.py
  tests/test_pipeline_files.py
  tests/test_spidermiddleware_base.py
Labels: cleanup

#7037 Deprecate the spider arg of downloader middleware methods.
  docs/topics/downloader-middleware.rst
  scrapy/core/downloader/middleware.py
  scrapy/downloadermiddlewares/cookies.py
  scrapy/downloadermiddlewares/defaultheaders.py
  scrapy/downloadermiddlewares/downloadtimeout.py
  scrapy/downloadermiddlewares/httpauth.py
  scrapy/downloadermiddlewares/httpcache.py
  scrapy/downloadermiddlewares/httpcompression.py
  scrapy/downloadermiddlewares/httpproxy.py
  scrapy/downloadermiddlewares/offsite.py
  scrapy/downloadermiddlewares/redirect.py
  scrapy/downloadermiddlewares/retry.py
  scrapy/downloadermiddlewares/robotstxt.py
  scrapy/downloadermiddlewares/stats.py
  scrapy/downloadermiddlewares/useragent.py
  tests/test_downloadermiddleware.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_downloadermiddleware_defaultheaders.py
  tests/test_downloadermiddleware_downloadtimeout.py
  tests/test_downloadermiddleware_httpauth.py
  tests/test_downloadermiddleware_httpcache.py
  tests/test_downloadermiddleware_httpcompression.py
  tests/test_downloadermiddleware_httpproxy.py
  tests/test_downloadermiddleware_offsite.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_downloadermiddleware_retry.py
  tests/test_downloadermiddleware_robotstxt.py
  tests/test_downloadermiddleware_stats.py
  tests/test_downloadermiddleware_useragent.py
  tests/test_middleware.py
  tests/test_request_attribute_binding.py
  tests/test_request_cb_kwargs.py
  tests/test_spidermiddleware_referer.py
Labels: cleanup

#7050 Drop PyPy 3.10 support, restore coverage for subprocesses
  .github/workflows/tests-ubuntu.yml
  pyproject.toml
  tox.ini
Labels: CI, cleanup

#7058 docs: Add Edit on GitHub
  docs/conf.py
Labels: docs
