Repository scrapy/scrapy, pull requests merged in 2025-01, with the labels that each got.

#6607 Install libjpeg-dev on pinned envs to be able to install Pillow.
  .github/workflows/tests-ubuntu.yml
Labels: bug, CI

#6609 Switch CI to codecov/codecov-action and enable it on Windows.
  .github/workflows/tests-macos.yml
  .github/workflows/tests-ubuntu.yml
  .github/workflows/tests-windows.yml
Labels: enhancement, CI

#6526 Improve internal refs to scrapy.Request and scrapy.Selector
  docs/conf.py
  docs/news.rst
  docs/topics/downloader-middleware.rst
  docs/topics/dynamic-content.rst
  docs/topics/exceptions.rst
  docs/topics/request-response.rst
  docs/topics/selectors.rst
  scrapy/core/scheduler.py
  scrapy/http/request/__init__.py
  scrapy/http/response/__init__.py
  scrapy/http/response/text.py
  scrapy/loader/__init__.py
  scrapy/utils/request.py
Labels: bug, docs

#6610 Fix and speed up subprocess coverage tracking
  pyproject.toml
  tests/__init__.py
  tox.ini
Labels: bug, enhancement, CI

#3426 Change unknown cmd message when outside project
  scrapy/cmdline.py
  tests/test_commands.py
Labels: enhancement

#4151 Deprecate BaseDupeFilter.log() and improve dupefilter docs
  docs/conf.py
  docs/topics/settings.rst
  scrapy/dupefilters.py
  tests/test_dupefilters.py
Labels: discuss, cleanup

#6606 Fix _pop_command_name and include tests
  scrapy/cmdline.py
  tests/test_commands.py
Labels: bug

#6608 Flexible severity of logging level when items are dropped
  docs/topics/settings.rst
  scrapy/exceptions.py
  scrapy/logformatter.py
  scrapy/settings/default_settings.py
  tests/test_logformatter.py
Labels: enhancement, logging

#6621 chore(docs): migrate to RTD template v3
  docs/conf.py
  docs/requirements.txt
Labels: enhancement, docs, CI

#6568 Fix Default SpiderLoader doesn't take into account addons
  docs/topics/addons.rst
  docs/topics/practices.rst
  docs/topics/settings.rst
  scrapy/addons.py
  scrapy/crawler.py
  tests/test_spiderloader/__init__.py
  tests/test_spiderloader/spiders_from_addons/__init__.py
  tests/test_spiderloader/spiders_from_addons/spider0.py
Labels: bug

#6613 Drop PyPy 3.9, add a pypy3-extra-deps CI job.
  .github/workflows/tests-ubuntu.yml
  tox.ini
Labels: enhancement, CI

#6631 Bump ruff, switch from black to ruff-format
  .pre-commit-config.yaml
  scrapy/commands/genspider.py
  scrapy/core/downloader/handlers/__init__.py
  scrapy/core/http2/stream.py
  scrapy/downloadermiddlewares/cookies.py
  scrapy/downloadermiddlewares/offsite.py
  scrapy/downloadermiddlewares/robotstxt.py
  scrapy/downloadermiddlewares/stats.py
  scrapy/extensions/telnet.py
  scrapy/http/headers.py
  scrapy/http/request/form.py
  scrapy/http/response/__init__.py
  scrapy/linkextractors/lxmlhtml.py
  scrapy/pipelines/files.py
  scrapy/selector/unified.py
  scrapy/settings/__init__.py
  scrapy/settings/default_settings.py
  scrapy/spidermiddlewares/offsite.py
  scrapy/squeues.py
  scrapy/utils/curl.py
  scrapy/utils/defer.py
  scrapy/utils/iterators.py
  scrapy/utils/log.py
  scrapy/utils/python.py
  tests/spiders.py
  tests/test_contracts.py
  tests/test_downloadermiddleware_httpproxy.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_downloaderslotssettings.py
  tests/test_engine.py
  tests/test_engine_stop_download_headers.py
  tests/test_exporters.py
  tests/test_feedexport.py
  tests/test_http_request.py
  tests/test_http_response.py
  tests/test_item.py
  tests/test_pipeline_files.py
  tests/test_pipeline_media.py
  tests/test_robotstxt_interface.py
  tests/test_selector.py
  tests/test_utils_response.py
  tests/test_utils_url.py
Labels: CI, cleanup

#6633 Fix error when running `scrapy bench`
  scrapy/commands/bench.py
  tests/test_commands.py
Labels: bug

#6634 Deprecate HTTP/1.0 code.
  scrapy/core/downloader/contextfactory.py
  scrapy/core/downloader/handlers/http10.py
  scrapy/core/downloader/webclient.py
  tests/test_core_downloader.py
  tests/test_downloader_handlers.py
  tests/test_webclient.py
Labels: cleanup

#6635 Remove scrapy.core.downloader.webclient._parse().
  scrapy/core/downloader/handlers/http11.py
  scrapy/core/downloader/handlers/http2.py
  scrapy/core/downloader/webclient.py
  tests/test_downloader_handlers.py
  tests/test_webclient.py
Labels: cleanup
