Repository scrapy/scrapy, pull requests merged in 2025-02, with the labels that each got.

#6646 Refactor EngineTest tests.
  tests/test_engine.py
  tests/test_engine_stop_download_bytes.py
  tests/test_engine_stop_download_headers.py
Labels: enhancement, CI

#6648 Optimize mockserver calls
  tests/test_closespider.py
  tests/test_crawl.py
  tests/test_downloader_handlers.py
  tests/test_downloaderslotssettings.py
  tests/test_feedexport.py
  tests/test_logformatter.py
  tests/test_pipeline_crawl.py
  tests/test_pipelines.py
  tests/test_proxy_connect.py
  tests/test_request_attribute_binding.py
  tests/test_request_cb_kwargs.py
  tests/test_request_left.py
  tests/test_signals.py
  tests/test_spidermiddleware_httperror.py
Labels: enhancement, CI

#6647 Refactor downloader tests
  pyproject.toml
  tests/test_downloader_handlers.py
  tests/test_downloader_handlers_http2.py
  tox.ini
Labels: enhancement, CI, cleanup

#6650 Remove a duplicate test.
  tests/test_downloadermiddleware_httpcache.py
Labels: CI, cleanup

#6664 Improve diagnostics for sync-only spider middlewares.
  scrapy/core/spidermw.py
  scrapy/utils/python.py
  tests/test_spidermiddleware.py
Labels: enhancement, asyncio

#6671 Fix getting annotations for _parse_sitemap() at the runtime.
  scrapy/spiders/sitemap.py
  tests/test_poet.py
Labels: bug

#6678 Preparations for switching to direct pytest.
  conftest.py
  pyproject.toml
  scrapy/utils/test.py
  tests/test_commands.py
  tests/test_contracts.py
  tests/test_crawl.py
  tests/test_crawler.py
  tests/test_downloadermiddleware.py
  tests/test_downloadermiddleware_ajaxcrawlable.py
  tests/test_downloadermiddleware_httpauth.py
  tests/test_downloadermiddleware_httpcache.py
  tests/test_downloadermiddleware_httpproxy.py
  tests/test_downloadermiddleware_offsite.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_engine.py
  tests/test_engine_stop_download_bytes.py
  tests/test_engine_stop_download_headers.py
  tests/test_exporters.py
  tests/test_extension_periodic_log.py
  tests/test_extension_throttle.py
  tests/test_http2_client_protocol.py
  tests/test_http_response.py
  tests/test_linkextractors.py
  tests/test_loader.py
  tests/test_loader_deprecated.py
  tests/test_middleware.py
  tests/test_pipelines.py
  tests/test_request_dict.py
  tests/test_scheduler_base.py
  tests/test_signals.py
  tests/test_squeues.py
  tests/test_utils_asyncio.py
  tests/test_utils_datatypes.py
  tests/test_utils_defer.py
  tests/test_utils_log.py
  tests/test_utils_misc/__init__.py
  tests/test_utils_python.py
  tests/test_utils_response.py
  tests/test_utils_signal.py
  tests/test_utils_template.py
  tests/test_utils_url.py
Labels: CI, cleanup

#6684 curl: add support for parsing -b,--cookie
  scrapy/utils/curl.py
  tests/test_utils_curl.py
Labels: enhancement

#6688 Add more docs for updating sync spider middlewares.
  docs/topics/coroutines.rst
  scrapy/core/spidermw.py
Labels: enhancement, docs, asyncio

#6618 Unknown encoding handling in HttpCompressionMiddleware, restore x-gzip support
  scrapy/downloadermiddlewares/httpcompression.py
  tests/test_downloadermiddleware_httpcompression.py
Labels: enhancement

#6680 Switch to pytest.raises().
  pyproject.toml
  scrapy/pqueues.py
  tests/test_crawler.py
  tests/test_downloader_handlers_http2.py
  tests/test_downloadermiddleware.py
  tests/test_downloadermiddleware_cookies.py
  tests/test_downloadermiddleware_httpauth.py
  tests/test_downloadermiddleware_httpcache.py
  tests/test_downloadermiddleware_httpcompression.py
  tests/test_downloadermiddleware_redirect.py
  tests/test_downloadermiddleware_retry.py
  tests/test_downloadermiddleware_robotstxt.py
  tests/test_exporters.py
  tests/test_feedexport.py
  tests/test_http2_client_protocol.py
  tests/test_http_headers.py
  tests/test_http_request.py
  tests/test_http_response.py
  tests/test_item.py
  tests/test_link.py
  tests/test_loader.py
  tests/test_loader_deprecated.py
  tests/test_logstats.py
  tests/test_pipeline_images.py
  tests/test_pqueues.py
  tests/test_request_dict.py
  tests/test_scheduler.py
  tests/test_scheduler_base.py
  tests/test_selector.py
  tests/test_settings/__init__.py
  tests/test_spider.py
  tests/test_spiderloader/__init__.py
  tests/test_spidermiddleware.py
  tests/test_spidermiddleware_httperror.py
  tests/test_spidermiddleware_referer.py
  tests/test_spiderstate.py
  tests/test_squeues.py
  tests/test_squeues_request.py
  tests/test_utils_conf.py
  tests/test_utils_curl.py
  tests/test_utils_datatypes.py
  tests/test_utils_deprecate.py
  tests/test_utils_gz.py
  tests/test_utils_iterators.py
  tests/test_utils_misc/__init__.py
  tests/test_utils_python.py
  tests/test_utils_response.py
Labels: CI

#6694 Add SpiderLoaderProtocol.
  scrapy/crawler.py
  scrapy/spiderloader.py
  scrapy/utils/spider.py
Labels: enhancement, typing
